### ISSUE TITLE
DeepPhys-Preprocessing

### ISSUE THREAD

**Issue by AnmolDuaAI** [TVS-AI/Pytorch_rppgs#10]
raw_video[:, :, :, 3] = video_normalize(raw_video[:, :, :, 3])
Why only first channel of appearance image is normalized ?

**Comment by SpicyYeol** [comment]
Dear AnmolDuaAI
Thank you for instructed in our project.
I That code is badly implemented.
I will fix it ASAP after finished my schedule.
Thank you for review my code.
Have a nice day.

**Comment by TVS-AI** [comment]
449ce1fea1b0d6f6378b458ea0bde81832cbf942

fixed
