### ISSUE TITLE
What shape deepphys accept

### ISSUE THREAD

**Issue by talhaanwarch** [TVS-AI/Pytorch_rppgs#7]
As physnet accept `batch, channel, length, width, height` i am confused what should be the shape to deepphys?

**Comment by SpicyYeol** [comment]
Deepphys accept `batch, width, height, channel` (None, 36, 36, 6).
The first 3channels are input of motion model.
extra 3channels are input of apperarnce model.


# input ( None, 36, 36, 6 )
#     MotionModel(_in[0])  ──┬──┬── [F]
#                            │  │
# AppearanceModel(_in[1])  ──┴──┘
